config/routes.rb
ErinMahoneyPhotoCom::Application.routes.draw do
  get "/series/:name" => "series#show", as: :series
  get "/about"        => "application#about", as: :about
  get "/contact"      => "application#contact", as: :contact
  get "/"             => "application#index"
end

app/models/series.rb
class Series < ActiveRecord::Base
  attr_accessible :display_name, :image_count, :index, :name

  default_scope order(:index)
  scope :default, where(index: 0).first
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :load_all_series

  def about; @about = true; end
  def contact; @contact = true; end

  private

  def load_all_series
    @all_series = Series.all
    @default    = @all_series.first
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_filter :load_series

  private

  def load_series
    @series = Series.where(name: params[:name]).first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.haml
.inline-block
  %img{ src: "https://s3.amazonaws.com/erinrademacher.com/about.jpg", width: "347", height: "520", alt: "" }
.inline-block.about
  %p
    Erin Mahoney graduated with a Bachelor of Fine Arts degree in Professional Photographic Illustration from the Rochester Institute of Technology. She specialized in studio photography and taught photography classes in Rochester, New York before moving out west to sunny San Francisco, California.
  %p
    She is now attending the Academy of Art University and dedicating her time to obtaining her Master of Fine Arts degree in Photography. After graduation, she aspires to teach in a university setting. In the meantime, she
    %a{ href: "http://www.mistakesandmalarkey.blogspot.com", target: "_blank" } blogs
    on matters of the heart and on her cat, Connor.

app/views/application/contact.html.haml
%img{ src: "https://s3.amazonaws.com/erinrademacher.com/contact.jpg", height: "420", width: "780" }
.inline-block.contact
  %p
    Email:
    %a{ href: "", id: "email" }
    %br
    %span
      Phone:
    %a{ href: "", id: "phone" }
    %br
    Blog:
    %a{ href: "http://www.mistakesandmalarkey.blogspot.com", target: "_blank" }
      Mistakes &amp; Malarkey

app/views/application/index.html.haml
%img{src: "https://s3.amazonaws.com/erinrademacher.com/home.jpg", width: "780", height: "520", alt: ""}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title ErinMahoneyPhoto.com

    %link{ rel: "shortcut icon", href: "/images/erinmahoneyphoto.com.ico" }
    = stylesheet_link_tag    "http://yui.yahooapis.com/3.4.1/build/cssreset/reset-min.css", :media => "all"
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags

  %body

    #container
      %h1#logo
        %a{ href: "/" }
          Erin
          %em Mahoney

      #navigation
        %ul
          %li#portfolio{class: "#{@series ? 'selected' : ''}" }
            = link_to "Portfolio", series_url(@default.name)

            %ul#portfolio_tier2{style: "display: #{@series ? 'block' : 'none'}" }
              - @all_series.each do |series|
                %li{ id: series.name, class: "#{@series == series ? 'selected' : ''}" }
                  = link_to series.display_name, series_url(series.name)

          %li#about{ class: "#{@about ? 'selected' : ''}" }
            = link_to "About", about_url

          %li#contact{ class: "#{@contact ? 'selected' : ''}" }
            = link_to "Contact", contact_url

      #content{class: "#{@series ? 'portfolio' : ''}"}

        = yield

      #copyright
        &copy;
        = Time.now.year
        Erin Mahoney

    %script
      = "var portfolio = #{@series ? 'true' : 'false'};"
    = javascript_include_tag "application"
    %script
      - if @series
        = "var imageViewer = new ImageViewer('#{@series.name}', #{@series.image_count});"

    - if Rails.env.production?
      %script{src: "/js/ga.js"}

app/views/series/show.html.haml
%img#portal{ src: "", width: "", height: "", alt: "" }

%div#thumbs